/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_opencv_UtilsToService */

#ifndef _Included_com_demo_opencv_UtilsToService
#define _Included_com_demo_opencv_UtilsToService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_opencv_UtilsToService
 * Method:    getEdge
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT jdoubleArray
    JNICALL Java_com_demo_opencv_UtilsToService_getEdge
    (JNIEnv * , jobject , jobject );

#ifdef __cplusplus
}
#endif
#endif
